### PR TITLE
Collapsable menu sections with transitions and icons

### PR DESCRIPTION
**Pull request by dennib**
Added has-children class with transitions on max-height.
Also added a caret icon that rotates according to opening status of the "section".

### CODE REVIEW

**Review by mazipan — APPROVED** [review]

**Comment by mazipan** [comment]
Can you add for other .ejs files @dennib ?

**Comment by dennib** [comment]
You're right, sure 😊
I will do it asap

**Comment by mazipan** [comment]
Ah I already refactor the project using 11ty, so it will reuse the template

**Comment by dennib** [comment]
Ah nice, perfect.

**Comment by mazipan** [comment]
FYI I am very open for any improvement, in term of tech or design.
You can create any improvement if you think it necessary 🙏

**Pull request merged**
